# Generated by nix-archiver
# This file pins packages to specific historical versions from Nixpkgs

{
  # nodejs v22.21.1 (commit: a761838c48dbb9ae4e6d4a784f56211d456b543d)
  nodejs = import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/a761838c48dbb9ae4e6d4a784f56211d456b543d.tar.gz";
  sha256 = "sha256-2Rxs8z0zcuxN/UEtFyZamfDGofEl9YIQHfthr8RfkFo=";
}) {};

  # python v3.10.7 (commit: 613a7dc8a7bd7c4d2b5fe391f17a7583decd0b4d)
  python = import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/613a7dc8a7bd7c4d2b5fe391f17a7583decd0b4d.tar.gz";
  sha256 = "sha256-gLc0tYpWi4GRICVO5uMoUxQET+G+gEA2m9+RQn/qttw=";
}) {};

  # go v1.24.12 (commit: 1223c633f4499cefcd6230fc100d6052f1cb093a)
  go = import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/1223c633f4499cefcd6230fc100d6052f1cb093a.tar.gz";
  sha256 = "sha256-yV+lOvAGkx6NApAjs1VDTx0iCzLUn9yWxaUvQ0i4hPw=";
}) {};

}
